<?php

namespace Database\Seeders;

use App\Models\Tool;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tools = [
            // Individu/Keluarga
            [
                'name' => 'Financial Planner Syariah',
                'category' => 'Individu/Keluarga',
                'description' => 'Alokasikan penghasilan sesuai kaidah syariah.',
                'inputs' => json_encode(['Penghasilan', 'Kebutuhan Pokok', 'Utang']),
                'outputs' => json_encode(['Alokasi Zakat', 'Sedekah', 'Tabungan Haji', 'Investasi Halal']),
                'benefits' => json_encode(['Mencapai keberkahan finansial.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/planner',
                'related_directory_ids' => json_encode(['m5']),
                'related_dalil_text' => 'Dan orang-orang yang apabila membelanjakan (harta), mereka tidak berlebihan, dan tidak (pula) kikir, dan adalah (pembelanjaan itu) di tengah-tengah antara yang demikian.',
                'related_dalil_source' => 'QS. Al-Furqan: 67',
            ],
            [
                'name' => 'Life Planner Islami',
                'category' => 'Individu/Keluarga',
                'description' => 'Rencanakan tujuan hidup dunia & akhirat.',
                'inputs' => json_encode(['Visi', 'Misi', 'Target Ibadah', 'Target Karir']),
                'outputs' => json_encode(['Roadmap hidup seimbang']),
                'benefits' => json_encode(['Hidup lebih terarah dan bermakna.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/life-planner',
                'related_directory_ids' => json_encode(['p1']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Parenting Islami Assistant',
                'category' => 'Individu/Keluarga',
                'description' => 'Panduan mendidik anak sesuai sunnah.',
                'inputs' => json_encode(['Usia Anak', 'Isu Perkembangan']),
                'outputs' => json_encode(['Saran Praktis', 'Doa', 'Kisah Teladan']),
                'benefits' => json_encode(['Membentuk generasi Rabbani.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/parenting',
                'related_directory_ids' => json_encode(['m4']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Kalkulator Waris Islami',
                'category' => 'Individu/Keluarga',
                'description' => 'Hitung pembagian waris sesuai faraid.',
                'inputs' => json_encode(['Harta warisan', 'daftar ahli waris']),
                'outputs' => json_encode(['Porsi waris setiap ahli waris']),
                'benefits' => json_encode(['Menghindari sengketa dan menegakkan keadilan.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/waris',
                'related_directory_ids' => json_encode(['m5', 'q3']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            // Bisnis Islami
            [
                'name' => 'POS Syariah',
                'category' => 'Bisnis Islami',
                'description' => 'Sistem kasir dengan validasi akad & produk halal.',
                'inputs' => json_encode(['Produk', 'Transaksi']),
                'outputs' => json_encode(['Laporan Penjualan Halal']),
                'benefits' => json_encode(['Memastikan transaksi bisnis sesuai syariah.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/pos',
                'related_directory_ids' => json_encode(['q1']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'HR Payroll Syariah',
                'category' => 'Bisnis Islami',
                'description' => 'Manajemen penggajian dengan komponen syari.',
                'inputs' => json_encode(['Data Karyawan', 'Kehadiran']),
                'outputs' => json_encode(['Slip Gaji (termasuk potongan zakat profesi)']),
                'benefits' => json_encode(['Keadilan dan ketepatan waktu dalam upah.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/payroll',
                'related_directory_ids' => json_encode(['s1', 'q3']),
                'related_dalil_text' => 'Berikan kepada seorang pekerja upahnya sebelum keringatnya kering.',
                'related_dalil_source' => 'HR. Ibnu Majah',
            ],
            [
                'name' => 'CRM Islami',
                'category' => 'Bisnis Islami',
                'description' => 'Manajemen hubungan pelanggan dengan adab.',
                'inputs' => json_encode(['Data Pelanggan', 'Interaksi']),
                'outputs' => json_encode(['Segmentasi Pelanggan', 'Riwayat Komunikasi']),
                'benefits' => json_encode(['Membangun loyalitas pelanggan dengan akhlak mulia.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/crm',
                'related_directory_ids' => json_encode(['s2']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Supply Chain Halal Tracker',
                'category' => 'Bisnis Islami',
                'description' => 'Lacak kehalalan produk dari hulu ke hilir.',
                'inputs' => json_encode(['Data Supplier', 'Sertifikat Halal', 'Proses Produksi']),
                'outputs' => json_encode(['Dashboard Ketertelusuran Halal']),
                'benefits' => json_encode(['Menjamin kehalalan produk bagi konsumen.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/halal-tracker',
                'related_directory_ids' => json_encode(['q1', 'm5']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Analisis Kelayakan Bisnis Syariah',
                'category' => 'Bisnis Islami',
                'description' => 'Evaluasi ide bisnis dari perspektif syariah dan pasar.',
                'inputs' => json_encode(['Model bisnis', 'proyeksi keuangan']),
                'outputs' => json_encode(['Skor kelayakan', 'rekomendasi perbaikan']),
                'benefits' => json_encode(['Mengurangi risiko dan meningkatkan potensi sukses.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/bisnis-analisis',
                'related_directory_ids' => json_encode(['p1', 'q2']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            // Lembaga/Komunitas
            [
                'name' => 'Manajemen Masjid Digital',
                'category' => 'Lembaga/Komunitas',
                'description' => 'Kelola jadwal, keuangan, and kegiatan masjid.',
                'inputs' => json_encode(['Jadwal Kajian', 'Laporan Infaq']),
                'outputs' => json_encode(['Kalender Kegiatan', 'Laporan Keuangan Transparan']),
                'benefits' => json_encode(['Meningkatkan efisiensi dan transparansi DKM.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/masjid',
                'related_directory_ids' => json_encode(['q1', 'p2']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Wakaf Manager',
                'category' => 'Lembaga/Komunitas',
                'description' => 'Platform manajemen aset dan program wakaf.',
                'inputs' => json_encode(['Data Aset Wakaf', 'Program Pemberdayaan']),
                'outputs' => json_encode(['Laporan Produktivitas Wakaf']),
                'benefits' => json_encode(['Optimalisasi manfaat wakaf untuk umat.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/wakaf',
                'related_directory_ids' => json_encode(['m5']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Shariah Governance Toolkit',
                'category' => 'Lembaga/Komunitas',
                'description' => 'Alat bantu untuk Dewan Pengawas Syariah (DPS).',
                'inputs' => json_encode(['Produk Baru', 'Isu Kepatuhan']),
                'outputs' => json_encode(['Checklist Kepatuhan', 'Draft Opini Syariah']),
                'benefits' => json_encode(['Mempermudah proses audit dan pengawasan syariah.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/governance',
                'related_directory_ids' => json_encode(['q1', 'q2', 'p4']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Manajemen Kurban Terpadu',
                'category' => 'Lembaga/Komunitas',
                'description' => 'Organisir proses kurban dari pendaftaran hingga distribusi.',
                'inputs' => json_encode(['Data pekurban', 'data mustahik']),
                'outputs' => json_encode(['Laporan distribusi daging kurban']),
                'benefits' => json_encode(['Transparansi dan pemerataan dalam ibadah kurban.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/kurban',
                'related_directory_ids' => json_encode(['q1', 'q3']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            // Keuangan/Investasi
            [
                'name' => 'Zakat Manager Pro',
                'category' => 'Keuangan/Investasi',
                'description' => 'Hitung dan distribusikan berbagai jenis zakat.',
                'inputs' => json_encode(['Data Harta', 'Data Mustahik']),
                'outputs' => json_encode(['Laporan Perhitungan & Distribusi Zakat']),
                'benefits' => json_encode(['Memastikan akurasi dan kepatuhan dalam berzakat.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/zakat',
                'related_directory_ids' => json_encode(['m5']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Shariah Stock Screener',
                'category' => 'Keuangan/Investasi',
                'description' => 'Filter saham yang sesuai dengan kriteria syariah.',
                'inputs' => json_encode(['Indeks Saham']),
                'outputs' => json_encode(['Daftar Saham Halal']),
                'benefits' => json_encode(['Membantu investor membuat keputusan investasi yang berkah.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/screener',
                'related_directory_ids' => json_encode(['m5', 'p4']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Shariah Contract Generator',
                'category' => 'Keuangan/Investasi',
                'description' => 'Buat draf akad-akad muamalah (Murabahah, Ijarah, dll).',
                'inputs' => json_encode(['Para Pihak', 'Objek Akad', 'Ketentuan']),
                'outputs' => json_encode(['Dokumen Draf Akad']),
                'benefits' => json_encode(['Mempercepat dan menstandarisasi pembuatan akad.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/contract',
                'related_directory_ids' => json_encode(['q1']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Kalkulator Cicilan Syariah',
                'category' => 'Keuangan/Investasi',
                'description' => 'Simulasikan pembiayaan murabahah atau IMBT.',
                'inputs' => json_encode(['Harga barang', 'margin', 'tenor']),
                'outputs' => json_encode(['Tabel angsuran bulanan']),
                'benefits' => json_encode(['Transparansi pembiayaan tanpa riba.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/cicilan',
                'related_directory_ids' => json_encode(['q3']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            // Edukasi
            [
                'name' => 'LMS (Learning Management System) Syariah',
                'category' => 'Edukasi',
                'description' => 'Platform e-learning untuk konten-konten Islami.',
                'inputs' => json_encode(['Materi Kursus', 'Kuis']),
                'outputs' => json_encode(['Portal Belajar Interaktif']),
                'benefits' => json_encode(['Menyebarkan ilmu syariah secara efektif dan terstruktur.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/lms',
                'related_directory_ids' => json_encode(['m3']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Simulator Keputusan Syariah',
                'category' => 'Edukasi',
                'description' => 'Game simulasi untuk melatih pengambilan keputusan.',
                'inputs' => json_encode(['Studi Kasus Bisnis/Personal']),
                'outputs' => json_encode(['Skor Keputusan & Pembahasan Syariah']),
                'benefits' => json_encode(['Belajar fiqh muamalah dengan cara yang menarik.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/simulator',
                'related_directory_ids' => json_encode(['m3', 'q2']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Assessment Kompetensi Islami',
                'category' => 'Edukasi',
                'description' => 'Ukur pemahaman dan penerapan nilai-nilai Islam.',
                'inputs' => json_encode(['Jawaban Kuesioner']),
                'outputs' => json_encode(['Profil Kompetensi & Rekomendasi Pengembangan']),
                'benefits' => json_encode(['Alat untuk introspeksi dan perbaikan diri.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/assessment',
                'related_directory_ids' => json_encode(['s2', 'p4']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Generator Dalil Kontekstual',
                'category' => 'Edukasi',
                'description' => 'Temukan dalil Qur\'an & Hadits terkait topik tertentu.',
                'inputs' => json_encode(['Kata kunci (misal: "jual beli")']),
                'outputs' => json_encode(['Daftar dalil relevan beserta terjemahan']),
                'benefits' => json_encode(['Mempermudah riset dan pencarian landasan syariah.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/dalil',
                'related_directory_ids' => null,
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            // Sosial/Umat
            [
                'name' => 'Crowdfunding Wakaf Produktif',
                'category' => 'Sosial/Umat',
                'description' => 'Galang dana wakaf tunai untuk proyek umat.',
                'inputs' => json_encode(['Proposal Proyek']),
                'outputs' => json_encode(['Halaman Kampanye & Laporan Progres']),
                'benefits' => json_encode(['Mobilisasi dana umat untuk proyek berkelanjutan.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/crowdfunding',
                'related_directory_ids' => json_encode(['m5']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Platform Kolaborasi Halal',
                'category' => 'Sosial/Umat',
                'description' => 'Hubungkan produsen, supplier, dan konsumen halal.',
                'inputs' => json_encode(['Profil Bisnis', 'Kebutuhan Kemitraan']),
                'outputs' => json_encode(['Marketplace & Direktori Bisnis Halal']),
                'benefits' => json_encode(['Membangun ekosistem ekonomi halal yang kuat.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/kolaborasi',
                'related_directory_ids' => json_encode(['p2']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'AI Muamalah Assistant',
                'category' => 'Sosial/Umat',
                'description' => 'Chatbot untuk menjawab pertanyaan dasar fiqh muamalah.',
                'inputs' => json_encode(['Pertanyaan Pengguna']),
                'outputs' => json_encode(['Jawaban berdasarkan referensi terpercaya']),
                'benefits' => json_encode(['Akses cepat terhadap informasi syariah.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/ai-assistant',
                'related_directory_ids' => json_encode(['m3']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
            [
                'name' => 'Sistem Distribusi Infaq & Sedekah',
                'category' => 'Sosial/Umat',
                'description' => 'Manajemen penyaluran dana sosial secara terarah dan tercatat.',
                'inputs' => json_encode(['Data donatur', 'data penerima manfaat']),
                'outputs' => json_encode(['Peta distribusi', 'laporan dampak sosial']),
                'benefits' => json_encode(['Meningkatkan akuntabilitas dan efektivitas penyaluran.']),
                'sharia_basis' => null,
                'link' => 'https://example.com/distribusi',
                'related_directory_ids' => json_encode(['q1', 'q3']),
                'related_dalil_text' => null,
                'related_dalil_source' => null,
            ],
        ];

        foreach ($tools as $tool) {
            DB::table('tools')->insert(array_merge($tool, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Tools seeded: ' . Tool::count());
    }
}
